### PR TITLE
Fix wrong mixin type for DecimalQuantityFormField

### PR DESCRIPTION
**Pull request by ikseek**

### CODE REVIEW

**Comment by CarliJoy** [comment]
Thanks for notifying.
I changed a test a the changelog.

**Comment by CarliJoy** [comment]
I will wait with the next release given you find yet another bug 😉 
Can I ask you @ikseek how you use the app?

**Comment by ikseek** [comment]
@CarliJoy Sure!
I'm working on a business automation app which does some (surprise!) monetary calculation. I prefer to use pint for money units. The thing is just started so not much to tell, but I have strong feeling that I will have to switch to regular Decimal fields because I prefer to define different currencies as separate dimensions and most models will have currency selection (from different dimensions). Do you think fields with selectable dimension might be worth having in django-pint?

**Comment by CarliJoy** [comment]
@ikseek  sorry for the late reply.
What exactly do you mean be selectable dimension?
For your use case Money would be the dimension and the different currencies are the units -> correct?
Do you mean that you want to save the currency selected by the user in the database?
Maybe you can elaborate on this in an Issue? 

It sound definitely like something that could be part of django-pint.

**Comment by ikseek** [comment]
@CarliJoy I find having one "money" dimension too naive an approach for practical purposes. I define separate dimension for each currency (like currency_USD, currency_EUR etc.) to avoid any automatic conversion because in real world currency conversion rates are never constant, depend on many factors like who, where and when does the exchange. But pint has contexts that are fun to use for currency conversions. I even made nice small package that defines currencies in pint: https://github.com/ikseek/iso_4217 ; it's new and not used in the production yet.
In my project I will probably do calculations and accounting in different currencies and need to store the amount along with exact currency used for it. Also I would like to store currency rates that are ratios of different currencies (and thus different dimensions).

**Pull request merged**
